x=makeCacheMatrix()
x$set(matrix(1:4,2,2))
x$get()
cacheSolve(x) 
cacheSolve(x)
x$get() %*% cacheSolve(x)

y=makeCacheMatrix()
y$set(matrix(2:5,2,2))
y$get()
x$get()
cacheSolve(y) 
cacheSolve(y)
x$get() %*% cacheSolve(x)
y$get() %*% cacheSolve(y)
